// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`onGroupStart 1`] = `""`;

exports[`onGroupStart: examples 1`] = `
"[Describe]: examples

     [Log]: \\"testing in a group\\"
   [Stack]: at ../assembly/assembly/internal/Reflect/Reflect.attachStackTrace (wasm-function[45]:0x11fa)
            at ../assembly/assembly/internal/log/log<~lib/string/String> (wasm-function[63]:0x16eb)
            at start:assembly/jest-reporter~anonymous|0 (wasm-function[102]:0x2ac2)
            at ../assembly/assembly/internal/Describe/describe (wasm-function[104]:0x2adb)
            at start:assembly/jest-reporter (wasm-function[105]:0x2aec)
            at ~start (wasm-function[111]:0x2b25)
"
`;

exports[`onStart: start 1`] = `""`;

exports[`onTestFinish: examples example 1 1`] = `
" [Success]: ✔ example 1
"
`;

exports[`onTestFinish: examples log value 1`] = `
" [Success]: ✔ log value
     [Log]: \\"testing in a test\\"
   [Stack]: at ../assembly/assembly/internal/Reflect/Reflect.attachStackTrace (wasm-function[45]:0x11fa)
            at ../assembly/assembly/internal/log/log<~lib/string/String> (wasm-function[63]:0x16eb)
            at start:assembly/jest-reporter~anonymous|0~anonymous|1 (wasm-function[64]:0x16fb)
            at ../assembly/assembly/internal/call/__call (wasm-function[107]:0x2afe)
"
`;

exports[`onTestFinish: examples push an error to the error array 1`] = `
" [Success]: ✔ push an error to the error array
"
`;

exports[`onTestFinish: examples something fails 1`] = `
"    [Fail]: ✖ something fails
  [Actual]: -1
[Expected]: 42
 [Message]: Here is an example failure message.
   [Stack]: RuntimeError: unreachable
            at ../assembly/assembly/internal/assert/assert (wasm-function[48]:0x1261)
            at ../assembly/assembly/internal/Expectation/Expectation<i32>#toBe (wasm-function[51]:0x12a7)
            at start:assembly/jest-reporter~anonymous|0~anonymous|3 (wasm-function[67]:0x171b)
            at ../assembly/assembly/internal/call/__call (wasm-function[107]:0x2afe)
"
`;

exports[`onTestFinish: examples something negated fails 1`] = `
"    [Fail]: ✖ something negated fails
  [Actual]: 42
[Expected]: Not 42
 [Message]: 42 is 42
   [Stack]: RuntimeError: unreachable
            at ../assembly/assembly/internal/assert/assert (wasm-function[48]:0x1261)
            at ../assembly/assembly/internal/Expectation/Expectation<i32>#toBe (wasm-function[51]:0x12a7)
            at start:assembly/jest-reporter~anonymous|0~anonymous|6 (wasm-function[100]:0x2a5a)
            at ../assembly/assembly/internal/call/__call (wasm-function[107]:0x2afe)
"
`;

exports[`onTestFinish: examples this should throw but it does not 1`] = `
"    [Fail]: ✖ this should throw but it does not
 [Message]: it should throw
"
`;

exports[`onTestFinish: examples when two things should equal each other 1`] = `
"  [Throws]: ✔ when two things should equal each other RTrace: +9
"
`;

exports[`onTestStart: examples example 1 1`] = `""`;

exports[`onTestStart: examples log value 1`] = `""`;

exports[`onTestStart: examples push an error to the error array 1`] = `""`;

exports[`onTestStart: examples something fails 1`] = `""`;

exports[`onTestStart: examples something negated fails 1`] = `""`;

exports[`onTestStart: examples this should throw but it does not 1`] = `""`;

exports[`onTestStart: examples when two things should equal each other 1`] = `""`;
